id = "ec1013ff-2d5f-4860-8d25-64acb6c60587"
created_at = "2026-04-20T21:57:01.237237500+00:00"
title = "bootstrap"
state = "draft"
code_refs = [{ file = "tools/cli/spec-cli/src/cli/commands/bootstrap.rs", kind = "function", line_end = 202, line_start = 42, symbol = "cmd_bootstrap" }]
component = "spec"
parent = "1d6481ff-308b-45ca-ac91-4c2f8d5546f3"
scope = "public"
slug = "spec-cli/cli/commands/bootstrap"
type = "specification"
