id = "867cd511-5bb6-494f-8dff-a150f4953f02"
created_at = "2026-09-25T14:35:05.374487+00:00"
title = "Specification Move Reference Integrity"
state = "draft"
component = "spec-api"
parent = "7487a6b5-39c6-4114-a697-6ed0556e888e"
scope = "internal"
slug = "spec-api/cross-repository-reference-integrity"
type = "specification"
