id = "4066c5a3-3e04-4eeb-81a2-91fb8e53cc94"
created_at = "2026-04-20T21:57:01.820920300+00:00"
title = "spec-mcp"
state = "draft"
component = "spec"
scope = "public"
slug = "spec-mcp"
type = "specification"
