id = "8c2bbb42-4ca0-43a3-8196-334218bf543e"
created_at = "2026-04-20T22:38:29.684475900+00:00"
title = "spec-viewer: spec-tree component"
state = "draft"
component = "spec"
parent = "d8b515b8-86fd-4366-9fff-1946f43c3030"
scope = "component"
slug = "spec-viewer/spec-tree"
type = "specification"
