id = "788e91e4-32d7-4ff5-bf68-485235f8211f"
created_at = "2026-04-20T22:38:41.264382100+00:00"
title = "spec-editor"
state = "draft"
component = "spec"
scope = "system"
slug = "spec-editor"
type = "specification"
