id = "c5b11920-6ae8-4686-ae07-b8e9f8100bf8"
created_at = "2026-04-22T22:53:03.817810500+00:00"
title = "spec-viewer: theme settings"
state = "draft"
component = "spec"
parent = "d8b515b8-86fd-4366-9fff-1946f43c3030"
scope = "component"
slug = "spec-viewer/theme-settings"
type = "specification"
