id = "cbac783c-e3a1-4a31-ac11-a539b39164c5"
created_at = "2026-04-20T22:38:59.169573200+00:00"
title = "spec-editor: section editor"
state = "draft"
component = "spec"
parent = "788e91e4-32d7-4ff5-bf68-485235f8211f"
scope = "component"
slug = "spec-editor/section-editor"
type = "specification"
