id = "e82b9727-0ea2-4d1d-ab8a-98141f85caef"
created_at = "2026-08-23T14:47:46.546072500+00:00"
title = "Criterion Template Contract"
state = "draft"
component = "spec"
parent = "f1b8f01a-c7da-4a71-97c5-39519a7d7f38"
scope = "internal"
slug = "spec-system/component-oriented-contracts/criterion-template"
type = "specification"
