id = "1cf68c36-7f64-4d81-b553-1947b978fbe3"
created_at = "2026-05-25T19:55:53.722242800+00:00"
title = "generated documents"
state = "draft"
component = "spec"
parent = "86877b97-2df6-46b5-923d-a9e608655fed"
scope = "public"
slug = "spec-api/generated-documents"
type = "specification"
