id = "83094beb-d315-4b16-b132-3ae22a528422"
created_at = "2026-04-20T21:57:42.097078100+00:00"
title = "error"
state = "draft"
code_refs = [{ file = "crates/spec-api/src/error.rs", kind = "enum", line_end = 22, line_start = 4, symbol = "SpecError" }]
component = "spec"
parent = "86877b97-2df6-46b5-923d-a9e608655fed"
scope = "public"
slug = "spec-api/error"
type = "specification"
