id = "ffb89723-178b-435b-8591-c639d3c7d5dd"
created_at = "2026-04-20T22:38:53.178010500+00:00"
title = "spec-editor: coderef editor"
state = "draft"
component = "spec"
parent = "788e91e4-32d7-4ff5-bf68-485235f8211f"
scope = "component"
slug = "spec-editor/coderef-editor"
type = "specification"
