id = "18d7cbc2-d454-498b-9f10-9f1a0d320f2e"
created_at = "2026-04-20T22:38:50.299497200+00:00"
title = "spec-editor: body editor"
state = "draft"
component = "spec"
parent = "788e91e4-32d7-4ff5-bf68-485235f8211f"
scope = "component"
slug = "spec-editor/body-editor"
type = "specification"
